### ISSUE TITLE
Improve enable password handling

### ISSUE THREAD

**Issue by mtache** [arista-netdevops-community/anta#165]
Currently, enable password is passed as argument when starting ANTA, stored as an attribute in the InventoryDevice model, and used in the test code to enter in privileged mode when needed.
This issue is to explore if we could move this logic in the AntaInventory class, add an attribute (e.g. `device.privileged`) in the InventoryDevice model to define if the device session has been established with privileged mode (similar to `established` and `is_online`).
This way, if a test needs privileged mode, we could have a decorator to check the `device.privileged` attribute and remove all the logic in coroutines that uses the enable password.

**Comment by carl-baillargeon** [comment]
Hello @mtache, with the recent refactoring of test cases into classes, the enable password is handled in the `collect()` method of `InventoryDevice` so we don't need that logic in the test cases anymore. Would that be sufficient you think?

**Comment by mtache** [comment]
That's perfect ! Thank you !
Closing this issue.
