### ISSUE TITLE
Issuing Keyboard Interrupt while ANTA is running crashes EOS ConfigAgent

### ISSUE THREAD

**Issue by mtache** [arista-netdevops-community/anta#265]
While running ANTA, issuing CTRL+C will crash EOS ConfigAgent.
Agent logs show:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 108, in processRequest
    self._processRequestInternal( request )
  File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 138, in _processRequestInternal
    self._processRequestNonStreaming( procedure, params )
  File "/usr/lib/python2.7/site-packages/JsonRpcBase.py", line 174, in _processRequestNonStreaming
    os.write( self.outputFd_, i )
OSError: [Errno 32] Broken pipe
ERROR: [Errno 32] Broken pipe
```

**Comment by mtache** [comment]
https://bugs.python.org/issue39622

https://github.com/python/cpython/blob/3.11/Doc/library/asyncio-runner.rst#handling-keyboard-interruption

**Comment by carl-baillargeon** [comment]
Connection timeouts from HTTPX will also crash the ConfigAgent on EOS.

**Comment by mtache** [comment]
As per discussion with engineering:

> This isn't a crash. This is just an exception (that is handled) and printed for debug reasons. This just means that when ConfigAgent went to write the response the frontend client was no longer there, which is expected if the client has been terminated.
