### ISSUE TITLE
anta debug run-template runs the last parameter only

### ISSUE THREAD

**Issue by carl-baillargeon** [arista-netdevops-community/anta#272]
It looks like vlan_id 10 is not saved in template_params.

```
template_params = dict(zip(params[::2], params[1::2]))
print(template_params)
```

```
(.anta) ➜  anta git:(doc-0.6.0) ✗ anta debug run-template -d DC1-LEAF1A -t "show vlan {vlan_id}" vlan_id 10 vlan_id 20
{'vlan_id': '20'}
Run templated command 'show vlan {vlan_id}' with {'vlan_id': '20'} on DC1-LEAF1A
command='show vlan 20' version='latest' revision=None ofmt='json' output=None template=AntaTemplate(template='show vlan {vlan_id}', version='latest', revision=None, ofmt='json') failed=None params={'vlan_id': '20'}
{
    'vlans': {
        '20': {
            'name': 'VRFPROD_VLAN20',
            'dynamic': False,
            'status': 'active',
            'interfaces': {
                'Cpu': {'privatePromoted': False, 'blocked': None},
                'Port-Channel11': {'privatePromoted': False, 'blocked': None},
                'Vxlan1': {'privatePromoted': False, 'blocked': None}
            }
        }
    },
    'sourceDetail': ''
}
```

**Comment by carl-baillargeon** [comment]
> so indeed this PR broke it: #245
> 
> using `nargs=-1` in click means that the variadics args entered at the end will keep only the latest value
> 
> ```
> anta --log DEBUG debug run-template -d spine1 -t "show vlan {vlan_id}" vlan_id 10 toto 42      
> > {'vlan_id': '10', 'toto': '42'}
> 
> anta --log DEBUG debug run-template -d spine1 -t "show vlan {vlan_id}" vlan_id 10 toto 42 vlan_id 29 toto 1             
> > {'vlan_id': '29', 'toto': '1'}
> ```
> 
> which means it is less funcitonality than 0.5.0 but the syntax looks better.
> 
> Let's document the current behavior for 0.6.0 and see how to fix this longer term.
> 
> Thanks !

Sounds good!

**Comment by titom73** [comment]
Related PR #300

**Comment by carl-baillargeon** [comment]
Closing issue as this feature will not be implemented.
