### ISSUE TITLE
L3MTU test fails for dynamic VLANs

### ISSUE THREAD

**Issue by emilarista** [arista-netdevops-community/anta#329]
The L3MTU test fails for dynamically allocated SVIs used by SIRB VRFs because their MTU does not conform to the global knob or test input value.

It would be useful to be able to set different MTU values for different interface types, and possibly even for different individual interfaces, and also to be able to skip certain interfaces that do not conform to the standard MTU for whatever reason. I think this would be required for this test to be useful in any scenario, lab or real world.

**Comment by carl-baillargeon** [comment]
Thanks for the feedback! I also noticed that the test was catching unwanted management interfaces. We will refactor accordingly.
