### ISSUE TITLE
Pass `Input` to params when rendering a template rather than a dict loosing the types

### ISSUE THREAD

**Issue by gmuloc** [arista-netdevops-community/anta#386]
Addin a comment here to track an issue to see if we can pass `Input` to params when rendering a template rather than a dict loosing the types

_Originally posted by @gmuloc in https://github.com/arista-netdevops-community/anta/pull/381#discussion_r1322582608_

**Comment by mtache** [comment]
Does not work because template params are not necessarily test inputs (c.f. render())
