### ISSUE TITLE
Bug: Exception object not present in TestResult

### ISSUE THREAD

**Issue by carl-baillargeon** [arista-netdevops-community/anta#421]
The exception object is not set in the error attribute of TestResult when an exception occurs in `_collect`.
```
  {
    "name": "DC1-LEAF1A",
    "test": "VerifyAdverseDrops",
    "categories": [
      "hardware"
    ],
    "description": "Verifies there are no adverse drops on DCS7280E and DCS7500E",
    "result": "error",
    "messages": [
      "show hardware counter drop has failed: EapiCommandError (CLI command 2 of 2 'show hardware counter drop' failed: invalid command)"
    ],
    "error": "None", <---------- Here
    "custom_field": "None"
  },
  ```

It could be added in the `wrapper` function of `anta_test` when we check `self.failed_commands`.

**Comment by gmuloc** [comment]
Technically there could be multiple failed commands and the attribute `error` can handle only one exception. Which one should it be - or should we change the field to `errors` ?

**Comment by gmuloc** [comment]
@mtache - any objection about changing from `error` to `errors`?

**Comment by carl-baillargeon** [comment]
Also, if we do this, should we change the messages a little bit to be a little bit more concise?

**Comment by gmuloc** [comment]
discussed on a call - lets remove error from TestResult and messages should contain useful info.
