### ISSUE TITLE
anta get from-ansible request for --username attribut

### ISSUE THREAD

**Issue by CyrielRct** [arista-netdevops-community/anta#479]
Version 0.10 & 0.11

anta get from-ansible -i inventory.yml -o inventory_anta.yml                 
Usage: anta [OPTIONS] COMMAND [ARGS]...
Try 'anta --help' for help.

**Error: Missing option '--username'.**

**Workaround :** 
define ENV variables for ANTA_INVENTORY / ANTA_USERNAME and ANTA_PASSWORD

**Comment by gmuloc** [comment]
Hi @CyrielRct - thanks for opening this issue! 
We are aware of this and tracking it in this issue: https://github.com/arista-netdevops-community/anta/issues/355
with a draft PR #447 that should be merged in the next release.

Closing your issue as duplicated and will add it to the PR tracker.
