### ISSUE TITLE
feat: Support Python 3.12

### ISSUE THREAD

**Issue by mtache** [arista-netdevops-community/anta#645]
- [ ] Remove upper bounds of httpx in aio-eapi
    * https://github.com/jeremyschulman/aio-eapi/pull/17
- [ ] cvprac is not compatible with Python 3.12
    * waiting for new release as this https://github.com/aristanetworks/cvprac/pull/271 has merged

**Comment by gmuloc** [comment]
cvprac 1.4.x supports Python 3.12
