### ISSUE TITLE
Path selection and AVT tests are giving WARNING when running on cEOSLab

### ISSUE THREAD

**Issue by carl-baillargeon** [arista-netdevops-community/anta#670]
Should we skip these tests on cEOSlab and vEOS-lab?

![image](https://github.com/arista-netdevops-community/anta/assets/63206086/de6bf5d5-30ee-4c78-a631-8ab15f526076)

**Comment by gmuloc** [comment]
This works only on CloudEOS indeed

**Comment by gmuloc** [comment]
to be adresses in #601
